### ISSUE TITLE
I got error during uv setup

### ISSUE THREAD

**Issue by devilcoder01** [google/A2A#276]
I simple clone this repo and folllow the instruction to setup. But when I go on this directory
`cd samples/python/agents/google_adk` the run `uv run .` thien I go some wired output here it is

```
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\agents\google_adk\__main__.py", line 10, in <module>
    load_dotenv()
    ~~~~~~~~~~~^^
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\main.py", line 362, in load_dotenv
    return dotenv.set_as_environment_variables()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\main.py", line 93, in set_as_environment_variables
    if not self.dict():
           ~~~~~~~~~^^
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\main.py", line 76, in dict
    resolve_variables(raw_values, override=self.override)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\main.py", line 239, in resolve_variables
    for name, value in values:
                       ^^^^^^
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\main.py", line 85, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\main.py", line 25, in with_warn_for_invalid_lines
    for mapping in mappings:
                   ^^^^^^^^
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\parser.py", line 173, in parse_stream
    reader = Reader(stream)
  File "D:\WORK-FILE\GitHub_Projects\A2A\samples\python\.venv\Lib\site-packages\dotenv\parser.py", line 64, in __init__
    self.string = stream.read()
                  ~~~~~~~~~~~^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

How to fix this

**Comment by kthota-g** [comment]
The error seems to be an issue with loading .env file in your environment. Can you try saving the .env file with utf-8 encoding or delete .env and trying setting the environment variables to the shell?

**Comment by holtskinner** [comment]
This issue should be resolved in the SDK release

**Comment by vuminhoang** [comment]
@devilcoder01 @holtskinner 

I'm still encountering this issue (I open the repo on PyCharm on a Windows machine), but I've found a simple way to fix:
 - I deleted the current .env file in demo/ui/.env (this was a file I created using echo, or even by direct creation, and it still caused the error).
 - Then, I created a new .env file using Notepad, pasting in the necessary information.
 - When saving, I pressed “Save As”, selected  "All files" for the "Save as type" and set the encoding to “UTF-8” (you can find these two options in the save dialog).
 
Afterward, I moved that file into the demo/ui directory, and everything worked normally. The problem was likely with the file format; when writing directly, it was saved as UTF-16.
